### ISSUE TITLE
New post header (hero image)

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#415]
I tried a new header this morning & posted on gitter chan, but I gues most of you didn't see it

![without image](http://cl.ly/image/1m1I3s0k2C0S/Image%202015-05-15%20at%209.11.24%20am.png)
![with image](http://cl.ly/image/360s2s1n143a/Image%202015-05-15%20at%209.12.06%20am.png)

Notes:
- You will be able to control the text color (light or dark) with a flag
- maybe we should put meta below the image
- I plan to add another layout where image is before all texts (including title)

Any thoughts ?

**Comment by kud** [comment]
Really cool. It gives some "life" to the website.

**Comment by magsout** [comment]
like it, very good job

**Comment by bloodyowl** [comment]
maybe we should use a canvas & calculate the best text color for contrast at runtime by reducing the canvas to 1px & reading the dominant color?

**Comment by MoOx** [comment]
It might be a good enhancement indeed. But simple flags for now allow server side rendering. That said, we might handle that with a metalsmith plugin that read the image content.

**Comment by MoOx** [comment]
Version light avec gradient custom

![screen shot 2015-05-15 at 22 41 54](https://cloud.githubusercontent.com/assets/157534/7661524/9d615080-fb53-11e4-8923-4ac0a3af1634.png)

```yaml
header:
  light: true
  linearGradient: 160deg, rgb(250, 250, 250), rgba(214, 194, 162, 0.6)
  image: true
  credit: http://freebiesxpress.com/gallery/macbook-air-table-direct-stock-photo/
```

Ça vous parait correcte ?

j'hésite sur le light, p-e juste `text: "light"` ? Quoique non c'est pas mieux.
Pour info les gradient sont préfixé -webkit aussi.

si .credit présent, on consider que image est ok
