### ISSUE TITLE
Ensure window support

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#498]
We will have some trick to changes (like CNAME generation) but the `appveyor.yml` below should be the thing

```
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 4

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell"
  - cmd: "npm test"
```
